// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: csvinfo.proto

package proto;

public interface CsvOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.YuhaoWang.csv.proto.Csv)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string city = 2;</code>
   */
  java.lang.String getCity();
  /**
   * <code>string city = 2;</code>
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>string address = 3;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 3;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>int32 age = 4;</code>
   */
  int getAge();

  /**
   * <code>string city1 = 5;</code>
   */
  java.lang.String getCity1();
  /**
   * <code>string city1 = 5;</code>
   */
  com.google.protobuf.ByteString
      getCity1Bytes();

  /**
   * <code>string zipcode = 6;</code>
   */
  java.lang.String getZipcode();
  /**
   * <code>string zipcode = 6;</code>
   */
  com.google.protobuf.ByteString
      getZipcodeBytes();
}
